apiVersion: v1
kind: ReplicationController
metadata:
  name: memcached1
spec:
  replicas: 1
  selector:
    name: memcached1
  template:
    metadata:
      name: memcached1
      labels:
        name: memcached1
    spec:
      containers:
        - name: memcached1
          image: seldonio/memcached:0.1
          ports:
            - containerPort: 11211
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: memcached1
  labels:
    name: memcached1
    app: memcache
spec:
  type: LoadBalancer
  ports:
    - port: 11211
      targetPort: 11211
      protocol: TCP
  selector:
    name: memcached1
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: memcached2
spec:
  replicas: 1
  selector:
    name: memcached2
  template:
    metadata:
      name: memcached2
      labels:
        name: memcached2
    spec:
      containers:
        - name: memcached2
          image: seldonio/memcached:0.1
          ports:
            - containerPort: 11211
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: memcached2
  labels:
    name: memcached2
    app: memcache
spec:
  type: LoadBalancer
  ports:
    - port: 11211
      targetPort: 11211
      protocol: TCP
  selector:
    name: memcached2
