apiVersion: v1
kind: Pod
metadata:
  name: zookeeper
  labels:
    name: zookeeper
spec:
  containers:
    - name: zookeeper
      image: mattf/zookeeper
      ports:
        - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    name: zookeeper
spec:
  type: ClusterIP
  ports:
    - port: 2181
  selector:
    name: zookeeper
